parameters:
#    cjw_summer_camp.example.class: Cjw\SummerCampBundle\Example

services:
#    cjw_summer_camp.example:
#        class: %cjw_summer_camp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
